lib: fix coverity warnings
Error: RESOURCE_LEAK (CWE-772): [#def10]
authselect-1.1/src/lib/util/dir.c:193: alloc_fn: Storage is returned from allocation function "string_array_create".
authselect-1.1/src/lib/util/dir.c:193: var_assign: Assigning: "items" = storage returned from "string_array_create(1UL)".
authselect-1.1/src/lib/util/dir.c:258: leaked_storage: Variable "items" going out of scope leaks the storage it points to.
  256|       }
  257|
  258|->     return ret;
  259|   }
  260|

* False positive (assumed that ret == EOK in case of error which is not possible)
Error: CLANG_WARNING: [#def7]
authselect-1.1/src/lib/profiles/read.c:139:17: note: Assigned value is garbage or undefined
        *_dirfd = dirfd;
                ^ ~~~~~
  137|
  138|           *_location = location;
  139|->         *_dirfd = dirfd;
  140|
  141|           return EOK;

* False positive (assumed that ret == EOK in case of error which is not possible)
Error: CLANG_WARNING: [#def8]
authselect-1.1/src/lib/util/dir.c:200:21: warning: 1st function call argument is an uninitialized value
    while ((entry = readdir(dirstream)) != NULL) {
                    ^
authselect-1.1/src/lib/util/dir.c:200:21: note: 1st function call argument is an uninitialized value
    while ((entry = readdir(dirstream)) != NULL) {
                    ^       ~~~~~~~~~
  198|
  199|       errno = 0;
  200|->     while ((entry = readdir(dirstream)) != NULL) {
  201|           if (is_dot_dir(entry->d_name)) {
  202|               continue;

Error: CLANG_WARNING: [#def6]
authselect-1.1/src/cli/main.c:813:17: warning: Value stored to 'ret' is never read
                ret = ENOMEM;
                ^     ~~~~~~
athselect-1.1/src/cli/main.c:813:17: note: Value stored to 'ret' is never read
                ret = ENOMEM;
                ^     ~~~~~~
  811|               if (path == NULL) {
  812|                   ERROR("Out of memory!");
  813|->                 ret = ENOMEM;
  814|                   goto done;
  815|               }

* False positive (assumed that ret == EOK in case of error which is not possible)
Error: CLANG_WARNING: [#def11]
authselect-1.1/src/lib/util/dir.c:293:17: warning: Array access (from variable 'files') results in a null pointer dereference
    for (i = 0; files[i] != NULL; i++) {
                ^~~~~
* False positive (assumed that ret == EOK in case of error which is not possible)
Error: CLANG_WARNING: [#def12]
authselect-1.1/src/lib/util/file.c:420:15: warning: 1st function call argument is an uninitialized value
    tmpname = file_get_basename(tmpfile);